name: commitmsg-conform

on:
  workflow_call:

jobs:
  commitmsg-conform:
    permissions:
      statuses: write
      checks: write
      contents: read
      pull-requests: read
    uses: actionsforge/actions/.github/workflows/commitmsg-conform.yml@main
