name: markdown-lint

on:
  workflow_call:

jobs:
  markdown-lint:
    permissions:
      statuses: write
      checks: write
      contents: read
      pull-requests: read
    uses: actionsforge/actions/.github/workflows/markdown-lint.yml@main
